### ISSUE TITLE
Regarding Video Capture

### ISSUE THREAD

**Issue by bhavesh-srashtasoft** [infinum/Android-GoldenEye#32] opened 2019-05-09 13:38 UTC
Hiii,

I am getting error in library when i capturing image
when i capture first video that will shoot completed.
in after that i am getting exception surface can not be null.

**Comment by domagojkorman** [comment] 2019-05-09 13:53
Hi,

I need more information to fix the issue. Can you please provide steps how to reproduce the issue and on which device the issue happened (device name and Android version)? It would be awesome if you could also send stacktrace.

**Comment by bhavesh-srashtasoft** [comment] 2019-05-10 11:36
OK When i will record a video first time i will recording completly fine and playing
but when i am record video again then it will not playing properly

Getting Error Here 

private fun initMediaRecorder(file: File) {
    if (activity.hasAudioPermission().not()) {
        LogDelegate.log("Recording video without audio. Missing RECORD_AUDIO permission.")
    }
    mediaRecorder = MediaRecorder().buildCamera2Instance(activity, config, file).apply {
        setOnErrorListener { _, _, _ -> callback?.onError(MediaRecorderDeadException) }
    }
}

 override fun createSession(textureView: TextureView) {
        initTextureViewSurface(textureView)
        initMediaRecorder(file!!)
        /*
         * mediaRecorder.getSurface() returns new surface on every getter call.
         * That is why it is a must to save it to a variable and reuse it.
        */
        mediaSurface = mediaRecorder?.surface
        cameraDevice.createCaptureSession(listOf(surface, mediaSurface), stateCallback, AsyncUtils.backgroundHandler)
    }


You can check video from this link

Video To check issue
[Click here to see video](https://drive.google.com/file/d/15byGp0CzOiLSRFfMHQPY7lW9WnEczu4i/view?usp=sharing
)

and getting issue in all devices

**Comment by bhavesh-srashtasoft** [comment] 2019-05-14 12:02
Hiii Is anyone here ?

**Comment by domagojkorman** [comment] 2019-05-14 12:17
I need to look into the issue to see what is wrong. Thanks for detailed report.

In the meantime. Can you try forcing Camera1 API and see whether it works OK there?

Here is how you can do it - https://github.com/infinum/Android-GoldenEye#manually-set-camera-api

**Comment by bhavesh-srashtasoft** [comment] 2019-05-14 12:30
OK Let me try this

**Comment by bhavesh-srashtasoft** [comment] 2019-05-14 12:42
Gettting same error video is not recording

**Comment by bhavesh-srashtasoft** [comment] 2019-05-15 05:08
Hii @domagojkorman 
is there can you found any solutions?

**Comment by domagojkorman** [comment] 2019-05-15 08:53
Can you please provide stacktrace so I can debug and look into the issue? I did not manage to reproduce it myself.

**Comment by bhavesh-srashtasoft** [comment] 2019-05-15 12:13
In a log i am getting only exception
Which i already sent you and also sent you where is exception generate i also given you

**Comment by domagojkorman** [comment] 2019-05-15 14:33
You did not send a [stacktrace](https://developer.android.com/studio/debug/stacktraces). You simply copy/pasted the code where the issue is happening. 

I need a stacktrace so I can see the flow which caused the issue.

**Comment by domagojkorman** [comment] 2019-05-28 08:47
Closing as I could not reproduce the issue and the report was incomplete.

**Closed by domagojkorman** 2019-05-28 08:47 UTC
Labels: bug
